### Find All Students
GET http://localhost:3000/students

### Find All Students
GET http://localhost:3000/Profile/1

### Find All Users
GET http://localhost:3000/User/1

### Find All Users
GET http://localhost:3000/Post/1

### Find All Tutorials
GET http://localhost:3000/tutorials
### Find All Students by pagination
GET http://localhost:3000/students/paging/1/4


### Find one student by id
GET http://localhost:3000/students/1

### Create a new Student
POST http://localhost:3000/students
Content-Type: application/json

{
    "firstName": "chanthi",
    "lastName": "lach",
    "email": "chanthi@gmail.com",
    "address": "Phnom Penh"
}

### Create a new Tutorial
POST http://localhost:3000/tutorials
Content-Type: application/json

{
    "title": "Learn HTML, CSS, and JavaScript",
    "type": "Frontend",
    "description": "Learn HTML, CSS, and JavaScript for beginning and end",
    "published": false
}

### create user with profile 
POST http://localhost:3000/User
Content-Type: application/json

{
  "email": "sokhour5@gmail.com",
  "name": "sokhour Lach",
  "bio": "sokhour's bio"
}

### create user with post
POST http://localhost:3000/User
Content-Type: application/json

{
  "email": "kaka10@gmail.com",
  "name": "kaka Lo",
  "posts": [
    { "title": "Java Tutorial",
     "content": "Content 1" 
     },
    { "title": "Post 2", 
    "content": "Content 2" 
    }
  ]
}


